controller_list:
  - name: fake_tuto_hand_controller
    joints:
      - finger_joint
  - name: fake_tuto_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint